const categorySections = [
  {
    title: "Seasonal & Holidays 🎉",
    items: [
      {
        name: "New Year’s Day",
        emoji: "🎆",
        color: "bg-blue-100",
        slug: "newyear",
        keywords: ["new year", "año nuevo", "2025", "celebration", "fiesta"],
      },
      {
        name: "Valentine’s Day",
        emoji: "💘",
        color: "bg-pink-200",
        slug: "valentines",
        keywords: ["valentine", "amor", "heart", "corazón", "san valentín"],
      },
      {
        name: "Easter",
        emoji: "🐣",
        color: "bg-purple-100",
        slug: "easter",
        keywords: ["easter", "pascua", "eggs", "huevos", "resurrection"],
      },
      {
        name: "Halloween",
        emoji: "🎃",
        color: "bg-orange-200",
        slug: "halloween",
        keywords: ["halloween", "dulce o trato", "costume", "disfraz", "pumpkin"],
      },
      {
        name: "Thanksgiving",
        emoji: "🦃",
        color: "bg-amber-200",
        slug: "thanksgiving",
        keywords: ["thanksgiving", "acción de gracias", "turkey", "gratitude"],
      },
      {
        name: "Christmas",
        emoji: "🎄",
        color: "bg-green-100",
        slug: "christmas",
        keywords: [
          "christmas",
          "navidad",
          "christmas tree",
          "árbol de navidad",
          "xmas",
        ],
      },
    ],
  },
  {
    title: "Love & Emotions 💖",
    items: [
      {
        name: "Love & Romance",
        emoji: "💌",
        color: "bg-rose-200",
        slug: "love-romance",
        keywords: ["love", "amor", "romance", "relationship", "relación"],
      },
      {
        name: "Anniversary",
        emoji: "💍",
        color: "bg-pink-100",
        slug: "anniversary",
        keywords: ["anniversary", "aniversario", "celebration", "celebración"],
      },
      {
        name: "I Miss You",
        emoji: "💭",
        color: "bg-sky-100",
        slug: "missing-you",
        keywords: [
          "miss you",
          "te extraño",
          "extrañar",
          "missing",
          "te echo de menos",
        ],
      },
      {
        name: "Apology",
        emoji: "💐",
        color: "bg-yellow-100",
        slug: "apology",
        keywords: ["apology", "perdón", "lo siento", "sorry"],
      },
      {
        name: "Thinking of You",
        emoji: "☁️",
        color: "bg-indigo-100",
        slug: "thinking-of-you",
        keywords: [
          "thinking",
          "pensando en ti",
          "thinking of you",
          "pensamiento",
        ],
      },
      {
        name: "Encouragement",
        emoji: "🌟",
        color: "bg-lime-100",
        slug: "encouragement",
        keywords: ["encouragement", "ánimo", "motivation", "motivación"],
      },
    ],
  },
  {
    title: "Family & Relationships 👨‍👩‍👧‍👦",
    items: [
      {
        name: "Mother’s Day",
        emoji: "🌸",
        color: "bg-pink-200",
        slug: "mothers-day",
        keywords: ["mother", "mamá", "mother’s day", "día de la madre"],
      },
      {
        name: "Father’s Day",
        emoji: "👔",
        color: "bg-blue-200",
        slug: "fathers-day",
        keywords: ["father", "padre", "father’s day", "día del padre"],
      },
      {
        name: "New Baby",
        emoji: "👶",
        color: "bg-sky-200",
        slug: "new-baby",
        keywords: ["baby", "bebé", "new baby", "recién nacido"],
      },
      {
        name: "Grandparents",
        emoji: "👵",
        color: "bg-yellow-200",
        slug: "grandparents",
        keywords: ["grandparent", "abuelo", "abuela", "grandparents day"],
      },
    ],
  },
  {
    title: "Work & Professional 💼",
    items: [
      {
        name: "Teacher’s Day",
        emoji: "🍎",
        color: "bg-rose-100",
        slug: "teachers-day",
        keywords: ["teacher", "maestro", "profesor", "teacher’s day"],
      },
      {
        name: "Nurses Week",
        emoji: "🩺",
        color: "bg-teal-200",
        slug: "nurses-week",
        keywords: ["nurse", "enfermera", "nurses week", "semana de enfermería"],
      },
      {
        name: "Doctor’s Day",
        emoji: "⚕️",
        color: "bg-blue-100",
        slug: "doctors-day",
        keywords: ["doctor", "médico", "doctor’s day", "día del médico"],
      },
      {
        name: "Police Appreciation",
        emoji: "👮‍♂️",
        color: "bg-gray-100",
        slug: "police-day",
        keywords: ["police", "policía", "law enforcement", "apreciación policía"],
      },
      {
        name: "Firefighters Day",
        emoji: "🚒",
        color: "bg-orange-100",
        slug: "firefighters-day",
        keywords: ["firefighter", "bombero", "firefighters day"],
      },
    ],
  },
  {
    title: "Everyday Moments 🌞",
    items: [
      {
        name: "Good Morning",
        emoji: "🌅",
        color: "bg-orange-100",
        slug: "good-morning",
        keywords: ["good morning", "buenos días", "morning"],
      },
      {
        name: "Good Night",
        emoji: "🌙",
        color: "bg-indigo-100",
        slug: "good-night",
        keywords: ["good night", "buenas noches", "night"],
      },
      {
        name: "Just Because",
        emoji: "💌",
        color: "bg-blue-100",
        slug: "just-because",
        keywords: ["just because", "solo porque", "anytime"],
      },
      {
        name: "Humor",
        emoji: "😂",
        color: "bg-rose-100",
        slug: "humor",
        keywords: ["humor", "funny", "chiste", "joke"],
      },
      {
        name: "Pets & Animals",
        emoji: "🐾",
        color: "bg-green-100",
        slug: "pets",
        keywords: ["pet", "mascota", "animal", "dog", "cat"],
      },
    ],
  },
];
