// 🌸 /lib/categories.js
export const MAIN_CATEGORIES = [
  {
    name: "Holidays",
    slug: "holidays",
    emoji: "🎄",
    color: "#FFF4E0",
    keywords: [
      "holiday", "holidays", "festivity", "celebration", "party",
      "newyear", "newyearseve", "christmas", "thanksgiving",
      "halloween", "easter", "independenceday", "july4th",
      "fireworks", "laborday", "memorialday", "veteransday",
      "columbusday", "presidentsday", "mlkday", "earthday",
      "womensday", "mothersday", "fathersday", "teachersday",
      "dayofthedead", "friendshipday", "kindnessday",
      "workersday", "carnival", "oktoberfest",
      "diwali", "ramadan", "heritagemonth", "lunarnewyear", "valentine"
    ],
    subcategories: [
      "New Year’s Eve",
      "Christmas",
      "Thanksgiving",
      "Halloween",
      "Easter",
      "Valentine’s Day",
      "Independence Day",
      "Labor Day",
      "Veterans Day",
      "Memorial Day",
      "Presidents Day",
      "Columbus Day",
      "Martin Luther King Jr. Day",
      "Earth Day",
      "Women’s Day",
      "Mother’s Day",
      "Father’s Day",
      "Teacher’s Day",
      "Friendship Day",
      "Kindness Day",
      "Day of the Dead",
      "Cultural Diversity Celebration",
      "Unity & Inclusion Day",
      "Oktoberfest",
      "Carnival",
      "Heritage Celebration",
      "Lunar New Year",
    ],
  },
  {
    name: "Love & Romance",
    slug: "love",
    emoji: "❤️",
    color: "#FFE8EE",
    keywords: [
      "love", "romance", "valentine", "couple", "relationship",
      "sweetheart", "kiss", "heart", "wedding", "engagement",
      "proposal", "anniversary", "together", "affection",
      "date", "forever", "partner", "soulmate", "missyou"
    ],
    subcategories: [
      "Valentine’s Day",
      "Anniversary",
      "Wedding",
      "Engagement",
      "Proposal",
      "Romantic Date",
      "Together Forever",
      "Love You",
      "Miss You",
      "Hug & Kiss",
      "Sweet Moments",
    ],
  },
  {
    name: "Celebrations & Special Moments",
    slug: "celebrations",
    emoji: "🎉",
    color: "#FFF7FF",
    keywords: [
      "celebration", "birthday", "party", "congratulations",
      "graduation", "success", "achievement", "babyshower",
      "newbaby", "genderreveal", "retirement", "newhome",
      "newjob", "promotion", "accomplishment", "milestone"
    ],
    subcategories: [
      "Birthday",
      "Graduation",
      "New Job",
      "Promotion",
      "New Home",
      "Baby Shower",
      "Gender Reveal",
      "Retirement",
      "Congratulations",
      "Achievement",
      "Milestone Celebration",
    ],
  },
  {
    name: "Work & Professional Life",
    slug: "work",
    emoji: "💼",
    color: "#EAF4FF",
    keywords: [
      "work", "career", "employee", "job", "bossday", "goal",
      "dedication", "achievement", "teamwork", "leader",
      "mentor", "teacher", "doctor", "nurse", "engineer",
      "coach", "artist", "entrepreneur", "retirement",
      "motivation", "colleague", "effort", "success", "business"
    ],
    subcategories: [
      "Congratulations at Work",
      "Promotion",
      "Boss Day",
      "Thank You Team",
      "Teacher Appreciation",
      "Nurse Appreciation",
      "Doctor Appreciation",
      "Coach Motivation",
      "Employee Recognition",
      "Workplace Positivity",
      "Professional Achievement",
      "Career Growth",
    ],
  },
  {
    name: "Condolences & Support",
    slug: "condolences",
    emoji: "🕊️",
    color: "#F8F8F8",
    keywords: [
      "condolence", "sympathy", "getwell", "healing", "encouragement",
      "appreciation", "thankyou", "remembrance", "gratitude", "support",
      "recovery", "loss", "memory", "hope", "care", "empathy", "thanks",
      "comfort", "kindness", "peace"
    ],
    subcategories: [
      "Condolence",
      "Healing Wishes",
      "Encouragement",
      "Support & Strength",
      "Gratitude",
      "Thank You",
      "Thinking of You",
      "Appreciation",
      "Peace & Comfort",
      "Hope & Healing",
    ],
  },
  {
    name: "Animals & Nature",
    slug: "animals",
    emoji: "🐾",
    color: "#E8FFF3",
    keywords: [
      "animals", "nature", "pets", "wildlife", "turtle", "cat", "dog",
      "elephant", "butterfly", "dolphin", "bird", "ocean", "forest",
      "garden", "eco", "flora", "fauna", "green", "planet", "yeti",
      "zoo", "bear", "lion", "tiger", "fish", "bee", "flower", "tree"
    ],
    subcategories: [
      "Pets",
      "Wildlife",
      "Ocean Life",
      "Forest Animals",
      "Farm Animals",
      "Birds",
      "Insects",
      "Endangered Species",
      "Cute Animals",
      "Nature Landscapes",
      "Sea Life",
      "Eco Love",
    ],
  },
  {
    name: "Seasons",
    slug: "seasons",
    emoji: "🍂",
    color: "#FFFBE5",
    keywords: [
      "seasons", "spring", "summer", "autumn", "fall", "winter",
      "rainy", "sunny", "snow", "beach", "mountain", "forest",
      "sunset", "travel", "vacation", "breeze", "bloom", "cold", "warm"
    ],
    subcategories: [
      "Spring",
      "Summer",
      "Autumn",
      "Winter",
      "Rainy Days",
      "Sunny Days",
      "Beach Season",
      "Travel Season",
      "Winter Wonderland",
      "Flower Bloom",
      "Snow Season",
    ],
  },
  {
    name: "Inspirational & Friendship",
    slug: "inspirational",
    emoji: "🌟",
    color: "#FFFBE5",
    keywords: [
      "inspiration", "motivation", "hope", "faith", "dream",
      "success", "happiness", "peace", "friendship", "teamwork",
      "goal", "believe", "gratitude", "positivity", "kindness",
      "community", "respect", "smile", "joy", "support", "mindfulness"
    ],
    subcategories: [
      "Friendship",
      "Motivation",
      "Peace & Mindfulness",
      "Positivity",
      "Happiness",
      "Gratitude",
      "Success & Goals",
      "Kindness",
      "Self Love",
      "Support & Encouragement",
      "Community Unity",
      "Joy & Smiles",
    ],
  },
];

// ✨ Utilidad para normalizar texto
export const normalize = (str) =>
  str
    ?.toLowerCase()
    .trim()
    .replace(/&/g, "and")
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "");
